import {
  AvatarItemRarity,
  AvatarItemType,
  RewardType,
} from "@prisma/client";

export const avatarCatalogSeed = [
  { id: "hair1", name: "Classic Cut", type: AvatarItemType.HAIR_STYLE, color: "#8B4513", cost: 0, rarity: AvatarItemRarity.COMMON, isDefault: true, sortOrder: 10 },
  { id: "hair2", name: "Curly Locks", type: AvatarItemType.HAIR_STYLE, color: "#FFD700", cost: 50, rarity: AvatarItemRarity.COMMON, isDefault: false, sortOrder: 20 },
  { id: "hair3", name: "Spiky Style", type: AvatarItemType.HAIR_STYLE, color: "#FF6347", cost: 100, rarity: AvatarItemRarity.RARE, isDefault: false, sortOrder: 30 },
  { id: "hair4", name: "Rainbow Hair", type: AvatarItemType.HAIR_STYLE, color: "#FF1493", cost: 200, rarity: AvatarItemRarity.EPIC, isDefault: false, sortOrder: 40 },
  { id: "shirt1", name: "Blue Tee", type: AvatarItemType.SHIRT, color: "#4169E1", cost: 0, rarity: AvatarItemRarity.COMMON, isDefault: true, sortOrder: 50 },
  { id: "shirt2", name: "Pink Shirt", type: AvatarItemType.SHIRT, color: "#FF69B4", cost: 30, rarity: AvatarItemRarity.COMMON, isDefault: false, sortOrder: 60 },
  { id: "shirt3", name: "Cool Jacket", type: AvatarItemType.SHIRT, color: "#000000", cost: 80, rarity: AvatarItemRarity.RARE, isDefault: false, sortOrder: 70 },
  { id: "shirt4", name: "Sparkly Top", type: AvatarItemType.SHIRT, color: "#FFD700", cost: 150, rarity: AvatarItemRarity.EPIC, isDefault: false, sortOrder: 80 },
  { id: "pants1", name: "Classic Jeans", type: AvatarItemType.PANTS, color: "#4169E1", cost: 0, rarity: AvatarItemRarity.COMMON, isDefault: true, sortOrder: 90 },
  { id: "pants2", name: "Shorts", type: AvatarItemType.PANTS, color: "#32CD32", cost: 25, rarity: AvatarItemRarity.COMMON, isDefault: false, sortOrder: 100 },
  { id: "pants3", name: "Cool Skirt", type: AvatarItemType.PANTS, color: "#FF69B4", cost: 60, rarity: AvatarItemRarity.RARE, isDefault: false, sortOrder: 110 },
  { id: "shoes1", name: "Sneakers", type: AvatarItemType.SHOES, color: "#FFFFFF", cost: 0, rarity: AvatarItemRarity.COMMON, isDefault: true, sortOrder: 120 },
  { id: "shoes2", name: "Boots", type: AvatarItemType.SHOES, color: "#8B4513", cost: 40, rarity: AvatarItemRarity.COMMON, isDefault: false, sortOrder: 130 },
  { id: "shoes3", name: "Sparkly Shoes", type: AvatarItemType.SHOES, color: "#FFD700", cost: 120, rarity: AvatarItemRarity.EPIC, isDefault: false, sortOrder: 140 },
  { id: "none", name: "No Accessory", type: AvatarItemType.ACCESSORY, color: "#CBD5E1", cost: 0, rarity: AvatarItemRarity.COMMON, isDefault: true, sortOrder: 150 },
  { id: "acc1", name: "Cool Glasses", type: AvatarItemType.ACCESSORY, color: "#000000", cost: 35, rarity: AvatarItemRarity.COMMON, isDefault: false, sortOrder: 160 },
  { id: "acc2", name: "Crown", type: AvatarItemType.ACCESSORY, color: "#FFD700", cost: 100, rarity: AvatarItemRarity.RARE, isDefault: false, sortOrder: 170 },
  { id: "acc3", name: "Magic Wand", type: AvatarItemType.ACCESSORY, color: "#FF1493", cost: 180, rarity: AvatarItemRarity.LEGENDARY, isDefault: false, sortOrder: 180 },
  { id: "bg1", name: "Default", type: AvatarItemType.BACKGROUND, color: "#87CEEB", cost: 0, rarity: AvatarItemRarity.COMMON, isDefault: true, sortOrder: 190 },
  { id: "bg2", name: "Space", type: AvatarItemType.BACKGROUND, color: "#191970", cost: 75, rarity: AvatarItemRarity.RARE, isDefault: false, sortOrder: 200 },
  { id: "bg3", name: "Rainbow", type: AvatarItemType.BACKGROUND, color: "#FF1493", cost: 150, rarity: AvatarItemRarity.EPIC, isDefault: false, sortOrder: 210 },
] as const;

export const rewardCatalogSeed = [
  {
    id: "screen_15",
    type: RewardType.SCREEN_TIME_MINUTES,
    title: "15 Minutes Screen Time",
    description: "Get 15 extra minutes of tablet time",
    cost: 50,
    rewardValue: 15,
    stockTotal: 10,
    stockRemaining: 8,
    sortOrder: 10,
  },
  {
    id: "screen_30",
    type: RewardType.SCREEN_TIME_MINUTES,
    title: "30 Minutes Screen Time",
    description: "Get 30 extra minutes of tablet time",
    cost: 90,
    rewardValue: 30,
    stockTotal: 5,
    stockRemaining: 4,
    sortOrder: 20,
  },
  {
    id: "screen_60",
    type: RewardType.SCREEN_TIME_MINUTES,
    title: "1 Hour Screen Time",
    description: "Get 1 hour of extra tablet time",
    cost: 150,
    rewardValue: 60,
    stockTotal: 3,
    stockRemaining: 3,
    sortOrder: 30,
  },
  {
    id: "roblox_100",
    type: RewardType.ROBLOX_CREDITS,
    title: "100 Robux",
    description: "Get 100 Robux for your Roblox account",
    cost: 200,
    rewardValue: 100,
    stockTotal: 2,
    stockRemaining: 2,
    sortOrder: 40,
  },
  {
    id: "roblox_400",
    type: RewardType.ROBLOX_CREDITS,
    title: "400 Robux",
    description: "Get 400 Robux for your Roblox account",
    cost: 700,
    rewardValue: 400,
    stockTotal: 1,
    stockRemaining: 1,
    sortOrder: 50,
  },
  {
    id: "roblox_800",
    type: RewardType.ROBLOX_CREDITS,
    title: "800 Robux",
    description: "Get 800 Robux for your Roblox account",
    cost: 1200,
    rewardValue: 800,
    stockTotal: 1,
    stockRemaining: 1,
    sortOrder: 60,
  },
] as const;
